In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\siya8\OneDrive\Desktop\Masters\Pre-masters\ML+ Data Science + Gen AI\Datasets\nlp_practice_dataset.csv")

In [3]:
df.head()

,review_id,customer_age,city,product,category,platform,rating,verified_purchase,review_text,sentiment
0,1,19,Delhi,Phone,Electronics,Flipkart,3,Yes,received the product yesterday,Neutral
1,2,23,Hyderabad,Smartwatch,Electronics,Amazon,3,Yes,purchased during a sale event,Neutral
2,3,53,Mumbai,Tablet,Wearables,Retail Store,4,Yes,absolutely love this product!!!!!!,Positive
3,4,18,Mumbai,Tablet,Accessories,Myntra,2,No,VeRy-----frustrated with the purchase,Negative
4,5,24,Pune,Smartwatch,Electronics,Myntra,5,No,absolutely love this product!!!!!!,Positive

In [4]:
df.shape

(500, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   review_id          500 non-null    int64
 1   customer_age       500 non-null    int64
 2   city               500 non-null    object
 3   product            500 non-null    object
 4   category           500 non-null    object
 5   platform           500 non-null    object
 6   rating             500 non-null    int64
 7   verified_purchase  500 non-null    object
 8   review_text        500 non-null    object
 9   sentiment          500 non-null    object
dtypes: int64(3), object(7)
memory usage: 39.2+ KB

In [6]:
df.isnull().sum()

review_id            0
customer_age         0
city                 0
product              0
category             0
platform             0
rating               0
verified_purchase    0
review_text          0
sentiment            0
dtype: int64

In [7]:
#select text column + NLP will focus on this 
df['review_text'].head()

0           received the product yesterday
1            purchased during a sale event
2       absolutely love this product!!!!!!
3    VeRy-----frustrated with the purchase
4       absolutely love this product!!!!!!
Name: review_text, dtype: object

In [8]:
# convert into lower case
df['review_text'] = df['review_text'].str.lower()
df['review_text'].head()

0           received the product yesterday
1            purchased during a sale event
2       absolutely love this product!!!!!!
3    very-----frustrated with the purchase
4       absolutely love this product!!!!!!
Name: review_text, dtype: object

In [9]:
# remove punctuation marks : ?, !
#regualar expression
import re 

#create a fucntion called remove-apunctuation
def remove_punctuation(text):
    ##
    cleaned_text = re.sub(r"[^\w\s]", "", text)
    return cleaned_text

In [10]:
#apply the remove_punctuation() fucntion to every row in the review_text column
df['review_text'] = df['review_text'].apply(remove_punctuation)

df['review_text'].head()

0      received the product yesterday
1       purchased during a sale event
2        absolutely love this product
3    veryfrustrated with the purchase
4        absolutely love this product
Name: review_text, dtype: object

In [11]:
## tokenization: use word_token

In [12]:
import nltk

nltk.download('punkt')  # pretrained model usde by nltk to split tect into sentences or words
nltk.download('punkt_tab') # newer version

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\siya8\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\siya8\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [13]:
from nltk.tokenize import word_tokenize

In [14]:
sample_review = df['review_text'][0]

tokens = word_tokenize(sample_review)

print(tokens)

['received', 'the', 'product', 'yesterday']

In [15]:
df['tokens'] = df['review_text'].apply(word_tokenize)

df[['review_text', 'tokens']].head()

                        review_text                                 tokens
0    received the product yesterday    [received, the, product, yesterday]
1     purchased during a sale event    [purchased, during, a, sale, event]
2      absolutely love this product      [absolutely, love, this, product]
3  veryfrustrated with the purchase  [veryfrustrated, with, the, purchase]
4      absolutely love this product      [absolutely, love, this, product]

In [16]:
# STOP WORD REMOVAL 

# sentence -> tokenization -> check words in stop_words -> remove stop_words

# download required once only, NLT stores it locally
nltk.download('stopwords')

from nltk.corpus import stopwords


stop_words = set(stopwords.words("english"))

print(stop_words)

{'off', "it'd", 'at', "don't", 'to', "i'd", 'because', 'isn', 'from', 'my', 'll', 'about', 'can', "hasn't", "should've", 'very', 'ain', 'herself', 'y', 'an', 'mightn', "i'll", 'needn', "you'd", 'whom', 'does', 'we', 'are', "she'll", 'hers', 'then', 'no', 'most', 'the', "i'm", 'if', 'wasn', "isn't", 'yourself', 'ours', 'than', 'had', 'after', "we'd", 'a', 'where', 'd', 'out', 'theirs', 'all', 'too', 'doing', 'their', 'do', 'didn', "needn't", "you're", 'doesn', 'while', "he's", 'himself', "haven't", 'down', 'until', "doesn't", "mightn't", 'over', "you'll", 'yours', 'be', "wasn't", 'won', 'nor', 'same', 'his', "hadn't", "i've", 'why', 'yourselves', 'he', 'that', 've', 'don', "it's", "they'd", 'you', 'she', 'these', 'only', "aren't", 'him', 'which', 'some', 'with', 'wouldn', 'but', "you've", 'shan', "they've", 'own', 'for', 'itself', 'each', 'have', 'how', 'just', 'hadn', 'now', 'o', 'has', 's', 'who', 'above', 'themselves', 'again', 'm', "we'll", 'will', 'ma', 'of', 'aren', 'am', 'such', 'your', "didn't", 'did', "it'll", 'not', "weren't", 'into', "we're", "we've", 'were', "wouldn't", 'i', 'against', 'other', 'its', "won't", 'what', 't', 'as', 'mustn', "they'll", 'they', 'ourselves', 'is', 'having', "shan't", "he'd", 'them', 'those', 'further', "she's", 're', 'her', 'hasn', 'it', 'when', 'during', 'this', 'any', 'in', 'on', "he'll", 'weren', 'being', 'our', "shouldn't", 'there', 'and', 'me', "she'd", 'so', 'couldn', 'before', "mustn't", 'up', 'been', 'shouldn', 'more', 'both', 'should', 'here', "they're", 'by', 'haven', 'once', "that'll", 'myself', 'or', "couldn't", 'few', 'through', 'below', 'was', 'under', 'between'}

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\siya8\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [17]:
#
def remove_stopwords(words):
    filtered_words = []

    for word in words:

        if word not in stop_words:

            filtered_words.append(word)

    return filtered_words

df["token_no_stopwords"] = df["tokens"].apply(remove_stopwords)

print(remove_stopwords)

<function remove_stopwords at 0x00000157FFD2DE40>

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfidf = TfidfVectorizer()

In [20]:
# convert reviews into vectors
X = tfidf.fit_transform(df['review_text'])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2086 stored elements and shape (500, 48)>

In [21]:
!pip install gensim

Requirement already satisfied: gensim in c:\users\siya8\anaconda3\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\siya8\anaconda3\lib\site-packages (from gensim) (2.3.5)
Requirement already satisfied: scipy>=1.7.0 in c:\users\siya8\anaconda3\lib\site-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\siya8\anaconda3\lib\site-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in c:\users\siya8\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [22]:
# Embedding techniques. 
from gensim.models import Word2Vec

In [23]:
word2vec_model = Word2Vec(
    sentences = df['token_no_stopwords'],
    vector_size = 100, 
    window = 5,
    min_count = 1
    
)

In [24]:
word2vec_model.wv['excellent']

array([-0.00167759, -0.00536595,  0.00951696, -0.00923054,  0.00441792,
        0.00535912, -0.00128608,  0.00976168,  0.00981329, -0.00591996,
       -0.00612537, -0.00711385, -0.00776434, -0.00278225, -0.00563833,
       -0.00870026,  0.00105692,  0.00327281,  0.00640341, -0.00326895,
       -0.00444884,  0.00105471,  0.00039411,  0.00805272,  0.00023678,
        0.00733291, -0.00858586,  0.00853373, -0.0019556 ,  0.00920156,
       -0.0075213 ,  0.00152091,  0.00138833, -0.00068358, -0.00535547,
       -0.00902761, -0.007366  , -0.00813917,  0.00179539,  0.00019176,
       -0.00191637,  0.00682838, -0.00232494, -0.00109693, -0.00877945,
       -0.01044754,  0.00907784, -0.00623533, -0.00623872,  0.0053986 ,
        0.006751  , -0.00720151,  0.00069806, -0.00618821,  0.00156064,
       -0.00435089, -0.00343431,  0.00224337,  0.00866557,  0.00670356,
       -0.00976013, -0.00587289,  0.00846717,  0.00234587, -0.00468016,
        0.00129553,  0.00978413, -0.00072119, -0.01018935,  0.00182529,
        0.00661321,  0.00658376,  0.00452596, -0.0055917 ,  0.00011703,
        0.00022256,  0.00468158, -0.00768369, -0.0082675 ,  0.00053141,
       -0.00903608,  0.00569123, -0.00063516,  0.01031143, -0.00528347,
       -0.00060588,  0.00817053, -0.00414715, -0.00474154,  0.0018609 ,
        0.00286893, -0.00258732,  0.00679967, -0.00777418,  0.00375512,
        0.00057439,  0.0088408 ,  0.00599056,  0.00691029,  0.00798181],
      dtype=float32)

In [25]:
word2vec_model.wv.most_similar("excellent")

[('daily', 0.27001821994781494),
 ('recommended', 0.2593139410018921),
 ('value', 0.16402603685855865),
 ('sale', 0.16247662901878357),
 ('delivery', 0.14155948162078857),
 ('amazing', 0.1225709319114685),
 ('product', 0.11535965651273727),
 ('delivery_was_on_time', 0.11185972392559052),
 ('worth', 0.09948042035102844),
 ('working', 0.0962732657790184)]

In [27]:
# get all words (features) learned by the tfidf vectorizer
feature_names = tfidf.get_feature_names_out()

#print vocab
print(feature_names)

['absolutely' 'after' 'amazing' 'and' 'daily' 'delivery'
 'delivery_was_on_time' 'description' 'disappointing' 'during' 'event'
 'exceeded' 'excellent' 'expectations' 'experience' 'fast' 'for' 'great'
 'highly' 'it' 'love' 'matches' 'money' 'not' 'perfectly' 'performance'
 'poor' 'product' 'purchase' 'purchased' 'quality' 'received'
 'recommended' 'sale' 'stopped' 'tasks' 'terrible' 'the' 'this' 'using'
 'value' 'veryfrustrated' 'week' 'with' 'working' 'works' 'worth'
 'yesterday']

In [29]:
import numpy as np 

#np.asarray() converts the sparse matrix result into a Numpy array 

avg_tfidf = np.asarray(X.mean(axis = 0)).ravel()

tfidf_scores = pd.DataFrame({
    'word' : feature_names,
    'avg_tfidf' : avg_tfidf   
})

tfidf_scores = tfidf_scores.sort_values('avg_tfidf', ascending = False)

print('Most Imp Words:')

print(tfidf_scores.head())

Most Imp Words:
                    word  avg_tfidf
37                   the   0.104791
27               product   0.101074
3                    and   0.081198
22                 money   0.067728
6   delivery_was_on_time   0.064000

In [30]:
print('Rare Words:')

print(tfidf_scores.tail(20))

Rare Words:
             word  avg_tfidf
20           love   0.034256
29      purchased   0.034000
9          during   0.034000
33           sale   0.034000
10          event   0.034000
13   expectations   0.033323
45          works   0.033323
11       exceeded   0.033323
24      perfectly   0.033323
8   disappointing   0.030901
25    performance   0.030901
26           poor   0.030901
18         highly   0.028736
32    recommended   0.028736
2         amazing   0.028736
36       terrible   0.028575
39          using   0.023409
35          tasks   0.023409
19             it   0.023409
4           daily   0.023409

In [31]:
# sentiment analysis using ML 
#define features
X = tfidf.fit_transform(df['review_text'])

y = df['sentiment']

In [33]:
# train-test split
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state =0)

In [35]:
# Train Naive Bayes

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [36]:
predictions = model.predict(X_test)

In [37]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, predictions)

print(accuracy)

1.0

In [39]:
# classification report 
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

    Negative       1.00      1.00      1.00        32
     Neutral       1.00      1.00      1.00        35
    Positive       1.00      1.00      1.00        33

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

In [44]:
# predict on new review 
new_review = {
    'This product is a waste of time !'
}

In [46]:
new_review_tfidf = tfidf.transform(new_review)

model.predict(new_review_tfidf)

array(['Positive'], dtype='<U8')